const PROGRAMS = [
  "RENEWABLE ENGINEERING",
  "COMPUTER SCIENCE & ENG.",
  "ELECTRICAL ENGINEERING",
  "MATHEMATICS",
  "MECHANICAL ENGINEERING",
  "GEOMATIC ENGINEERING",
  "GEOLOGICAL ENGINEERING",
  "MINING ENGINEERING",
  "MINERALS ENGINEERING",
  "ENV. & SAFETY ENG.",
  "PETROLEUM ENGINEERING",
  "GENERAL DRILLING",
];

const LEVELS = ["LEVEL 100", "LEVEL 200", "LEVEL 300", "LEVEL 400"];

const SEMESTERS = ["1ST SEMESTER", "2ND SEMESTER"];

export { PROGRAMS, LEVELS, SEMESTERS };
